
#define ID_APPMAIN	1024

#define ID_DISPLAY	(ID_APPMAIN+1)
#define ID_LISTWIN	(ID_APPMAIN+2)
#define ID_CLIENTWIN	(ID_APPMAIN+3)
#define ID_CHILDWIN	(ID_APPMAIN+128)

#define IDM_BITBUTTON	(ID_APPMAIN-4)
#define IDM_WINDOWSWITCH	(ID_APPMAIN-3)
#define IDM_PANESWITCH	(ID_APPMAIN-2)
#define IDM_EXIT	(ID_APPMAIN-1)

#define ID_FILEMENU	0
#define IDM_FILE	(ID_APPMAIN)
#define IDM_OPEN	(IDM_FILE+1)
#define IDM_SAVE	(IDM_FILE+2)
#define IDM_STRUCTINFO	(IDM_FILE+3)

#define ID_RECENTFILEPOS	5
#define IDM_RECENTFILE		(IDM_FILE+4)
#define IDM_RECENTFILELAST	(IDM_RECENTFILE+10)

#define ID_EDITMENU	1
#define IDM_EDIT	(ID_APPMAIN+16)
#define IDM_UNDO	(IDM_EDIT+1)
#define IDM_CUT		(IDM_EDIT+2)
#define IDM_COPY	(IDM_EDIT+3)
#define IDM_PASTE	(IDM_EDIT+4)

#define ID_OBJECTMENU	2
#define IDM_OBJECT	(ID_APPMAIN+24)
#define IDM_SEARCHOBJ	(IDM_OBJECT+1)
#define IDM_SEARCHPROP	(IDM_OBJECT+2)
#define IDM_SEARCHMETAPROP	(IDM_OBJECT+3)
#define IDM_SEARCHLINK	(IDM_OBJECT+4)
#define IDM_OBJADD	(IDM_OBJECT+5)
#define IDM_OBJREMOVE	(IDM_OBJECT+6)
#define IDM_EDITCHUNKS	(IDM_OBJECT+7)
#define IDM_IMPORTGMVL	(IDM_OBJECT+8)

#define ID_WINDOWMENU	3
#define IDM_WINDOW	(ID_APPMAIN+48)
#define IDM_CASCADE	(IDM_WINDOW+1)
#define IDM_TILEH	(IDM_WINDOW+2)
#define IDM_TILEV	(IDM_WINDOW+3)
#define IDM_ARRANGE	(IDM_WINDOW+4)

#define ID_HELPMENU	4
#define IDM_HELP	(ID_APPMAIN+64)
#define IDM_ABOUTBOX	(IDM_HELP+1)

#define IDM_BITFIELD	(ID_APPMAIN+128)
#define IDM_BITFIELDLAST	(IDM_BITFIELD+32)

#define IDS_OPENFILECAPTION	(ID_APPMAIN+1)
#define IDS_SAVEFILECAPTION	(ID_APPMAIN+2)
#define IDS_GAMSYSFILTER	(ID_APPMAIN+3)
#define IDS_XMLFILTER		(ID_APPMAIN+4)

#define ID_MENULABELS		(ID_APPMAIN+8)
#define IDS_UNDOREDO		(ID_MENULABELS+0)
#define IDS_ADDOBJECT		(ID_MENULABELS+1)
#define IDS_REMOBJECT		(ID_MENULABELS+2)
#define IDS_ADDPROPERTY		(ID_MENULABELS+3)
#define IDS_REMPROPERTY		(ID_MENULABELS+4)
#define IDS_ADDMETAPROP		(ID_MENULABELS+5)
#define IDS_REMMETAPROP		(ID_MENULABELS+6)
#define IDS_ADDLINK		(ID_MENULABELS+7)
#define IDS_REMLINK		(ID_MENULABELS+8)
#define IDS_ADDSTIMULUS		(ID_MENULABELS+9)
#define IDS_REMSTIMULUS		(ID_MENULABELS+10)
#define IDS_ADDRECEPTRON	(ID_MENULABELS+11)
#define IDS_REMRECEPTRON	(ID_MENULABELS+12)

#define ID_TABLABELS		(ID_APPMAIN+32)
#define IDS_PROPLABEL		(ID_TABLABELS+0)
#define IDS_MPLABEL		(ID_TABLABELS+1)
#define IDS_LINKLABEL		(ID_TABLABELS+2)
#define IDS_STIMLABEL		(ID_TABLABELS+3)
#define IDS_RCPTNLABEL		(ID_TABLABELS+4)

#define ID_COLUMNLABELS		(ID_APPMAIN+40)
#define IDS_COLNAME		(ID_COLUMNLABELS+0)
#define IDS_COLPRIORITY		(ID_COLUMNLABELS+1)
#define IDS_COLLINKID		(ID_COLUMNLABELS+2)
#define IDS_COLSOURCE		(ID_COLUMNLABELS+3)
#define IDS_COLDEST		(ID_COLUMNLABELS+4)
#define IDS_COLKIND		(ID_COLUMNLABELS+5)
#define IDS_COLSTIMULUS		(ID_COLUMNLABELS+6)
#define IDS_COLREACTION		(ID_COLUMNLABELS+7)
#define IDS_COLPROPAGATION	(ID_COLUMNLABELS+8)
#define IDS_COLINTENSITY	(ID_COLUMNLABELS+9)
#define IDS_COLINTENSITYMIN	(ID_COLUMNLABELS+10)
#define IDS_COLINTENSITYMAX	(ID_COLUMNLABELS+11)

#define ID_DIALOGTEXT		(ID_APPMAIN+80)
#define IDS_SEARCHOBJTITLE	(ID_DIALOGTEXT+1)
#define IDS_SEARCHOBJPROMPT	(ID_DIALOGTEXT+2)
#define IDS_ADDOBJTITLE		(ID_DIALOGTEXT+3)
#define IDS_ADDOBJPROMPT	(ID_DIALOGTEXT+4)
#define IDS_ADDPROPERTYTITLE	(ID_DIALOGTEXT+5)
#define IDS_ADDPROPERTYPROMPT	(ID_DIALOGTEXT+6)
#define IDS_ADDMETAPROPTITLE	(ID_DIALOGTEXT+7)
#define IDS_ADDMETAPROPPROMPT	(ID_DIALOGTEXT+8)
#define IDS_ADDLINKTITLE	(ID_DIALOGTEXT+9)
#define IDS_ADDLINKPROMPT	(ID_DIALOGTEXT+10)
#define IDS_ADDLINKDESTPROMPT	(ID_DIALOGTEXT+11)
#define IDS_ADDSTIMULUSTITLE	(ID_DIALOGTEXT+12)
#define IDS_ADDSTIMULUSPROMPT	(ID_DIALOGTEXT+13)
#define IDS_ADDRECEPTRONTITLE	(ID_DIALOGTEXT+14)
#define IDS_ADDRECEPTRONPROMPT	IDS_ADDSTIMULUSPROMPT
#define IDS_SEARCHPROPTITLE	(ID_DIALOGTEXT+15)
#define IDS_SEARCHMETAPROPTITLE	(ID_DIALOGTEXT+16)
#define IDS_SEARCHPROPPROMPT	IDS_ADDPROPERTYPROMPT
#define IDS_SEARCHMETAPROPPROMPT	IDS_ADDMETAPROPPROMPT

#define ID_OKBUTTON		(ID_APPMAIN+1)
#define ID_CANCELBUTTON		(ID_APPMAIN+2)
#define ID_LISTICONS		(ID_APPMAIN+3)

#define ID_STRINGINPUT		(ID_APPMAIN+8)
#define ID_LISTINPUT		(ID_APPMAIN+12)
#define ID_LINKINPUT		(ID_APPMAIN+16)
#define IDD_STATICTEXT		(ID_STRINGINPUT+1)
#define IDD_EDITTEXT		(ID_STRINGINPUT+2)
#define IDD_STATICLIST		(ID_STRINGINPUT+3)
#define IDD_EDITLIST		(ID_STRINGINPUT+4)

